name: hello
publish_to: none
environment:
  sdk: '>=2.0.0-dev <3.0.0'
dependencies:
  angel_migration: ^2.0.0-alpha
  angel_orm: ^2.0.0-dev
  angel_framework: ^2.1.1
  angel_serialize: ^2.0.0
  logger: ^0.9.1
  angel_websocket: ^2.0.3
dev_dependencies:
  angel_orm_generator: ^2.0.0-dev
  angel_serialize_generator: ^2.0.0
  build_runner: ^1.0.0