name: hello
publish_to: none
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  angel_migration: ^2.0.0-alpha
  angel_orm: ^2.1.0-beta.3
  angel_framework: ^2.1.1
  angel_serialize: ^2.2.3+3
  angel_websocket: ^2.0.3
  angel_auth: ^2.1.5+1
  angel_oauth2: ^2.3.0
  angel_orm_postgres:
    git:
      url: https://github.com/Fasuh/angel.git
      path: packages/orm/angel_orm_postgres
  angel_migration_runner:
    git:
      url: https://github.com/Fasuh/angel.git
      path: packages/orm/angel_migration_runner
  postgres: ^2.1.1
  angel_configuration: ^2.0.0
  password_hash: ^2.0.0
  corsac_jwt: ^0.2.2
  angel_production: ^1.0.0
  args: ^1.6.0
  common:
    path: ../common
dev_dependencies:
  angel_orm_generator: ^2.0.5
  angel_serialize_generator: ^2.5.0
  build_runner: ^1.10.0
  source_gen: ^0.9.5