// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'package:test/test.dart';
import 'helper/validators_test.dart' as classes_validators_test;

void main() {
  classes_validators_test.main();
}
