name: common
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  angel_model: ^1.0.3
  angel_orm: ^2.0.2
  angel_serialize: ^2.2.3+3
  angel_migration_runner:
    git:
      url: https://github.com/Fasuh/angel.git
      path: packages/orm/angel_migration_runner
  enum_to_string: ^1.0.9
dev_dependencies:
  angel_orm_generator: ^2.0.5
  angel_serialize_generator: ^2.5.0
  build_runner: ^1.10.0
  test: ^1.14.3

